### ISSUE TITLE
Allowlist/Exclude Certain Files

### ISSUE THREAD

**Issue by hf-kklein** [arma-actions/bom-check#3]
Is there a possibility to allowlist/exclude certain files from the check? Like an entire directory, or specific files or specific file endings?

**Comment by hf-kklein** [comment]
nearly 2 years after my question I stumbled accross this again.
here's my dirty fix

```yaml
name: Prevent ByteOrderMarks

on:
  push:
    branches:
      - main
  pull_request: { }

jobs:
  bom-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arma-actions/bom-check@v1
        name: Check for BOM
        with:
          path: "$(find \"$1\" -type f ! -path './path/to/a/file/that/is/utf8bomencoded')"
```

It's a bit hacky and the value of path is used as `$1` here:
https://github.com/arma-actions/bom-check/blob/2c6aad6bd43f4a74c69c467477a77a60af093580/entrypoint.sh#L10
